config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :photographers
  devise_for :users

  resources :photographers, only: [:index, :show, :edit, :update]

  resources :photographers, only: [] do
      resources :reviews, only: [:create, :destroy]

  end

  get 'about' => 'welcome#about'
  root 'welcome#index'


end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :photographers

  acts_as_mappable :default_units => :miles,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/photographer.rb
class Photographer < ActiveRecord::Base
  before_save {self.email = email.downcase}
  after_initialize { self.level ||= :standard}
  after_initialize { self.wttravel ||= false}

  validates :first_name, length: { minimum: 2 }, presence: true
  validates :last_name, length: { minimum: 2 }, presence: true
  validates :bio, length: { minimum: 5, maximum: 500 }, presence: true
  validates :zip, presence: true
  validates :yrs_experience, presence: true, numericality: true

  belongs_to :location
  has_many :reviews
  has_one :specialties

  acts_as_mappable #through: :location

  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  enum level: [:standard, :premium, :admin]
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :photographer

  #validates :rating, inclusion: { in: [0..5], message: "%{value} is not a valid vote." }, presence: true
  validates :comment, length: { minimum: 5 }, presence: true
  #validates :user, uniqueness: {scope: :photographer}, presence: true
  validates :photographer, presence: true
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
  belongs_to :photographers
end

app/models/user.rb
class User < ActiveRecord::Base
  after_initialize { self.level ||= :standard}

  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews

  enum level: [:standard, :premium, :admin]

  ratyrate_rater

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :first_name, :last_name, :bio, :website, :yrs_experience, :zip, :wttravel, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :first_name, :last_name, :password, :password_confirmation, :current_password) }
  end

  def require_sign_in
      unless current_user
          flash[:alert] = "You must be logged in to do that"

          redirect_to new_user_session_path
      end
  end
end

app/controllers/photographers_controller.rb
class PhotographersController < ApplicationController
  before_action :get_ip


  def index
    @zip_code = params[:search_zip_code]
    if @zip_code
      @photographers = Photographer.where(zip: @zip_code)
    else
      @photographers = Photographer.all
    end
  end

  def show
    @photographer = Photographer.find(params[:id])
  end

  def edit
    @photographer = Photographer.find(params[:id])
  end

  def update
    @photographer = Photographer.find(params[:id])
    @photographer.assign_attributes(photographer_params)

    if @photographer.save
      flash[:notice] = "Profile was updated."
      redirect_to [@photographer]
    else
      flash.now[:alert] = "There was an error updating your profile. Please try again."
      render :edit
    end
  end

  private

  def photographer_params
      params.require(:photographer).permit(:bio, :website, :yrs_experience, :zip, :wttravel)
  end

  def get_ip
    #@ip_address = Geocoders::MultiGeocoder.geocode(request.remote_ip)
  end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_sign_in
  before_action :authorize_user, only: [:destroy]

    def create
        @photographer = Photographer.find(params[:photographer_id])
        @review = @photographer.reviews.new(review_params)
        @review.user = current_user
        @new_review = Review.new

        if @review.save
            flash[:notice] = "Review saved successfully."
        else
            flash[:alert] = "Review failed to save."
        end

        redirect_to @photographer


    end

    def destroy
        @photographer = Photographer.find(params[:photographer_id])
        @review = @photographer.reviews.find(params[:id])

        if @review.destroy
            flash[:notice] = "Review was deleted successfully."
        else
            flash[:alert] = "Review couldn't be deleted. Try again."
        end
        redirect_to @photographer

    end

    private

    def review_params
        params.require(:review).permit(:comment, :rating)
    end

    def authorize_user
        review = Review.find(params[:id])
        @photographer = Photographer.find(params[:photographer_id])
        unless current_user == review.user || current_user.admin?
            flash[:alert] = "You do not have permission to delete this review."
            redirect_to @photographer
        end
    end
end

app/controllers/specialties_controller.rb
class SpecialtiesController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def about
  end

  def index
    @zip_code = params[:search_zip_code]
    if @zip_code
      @photographers = Photographer.where(zip: @zip_code)
    else
      @photographers = Photographer.all
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photographers_helper.rb
module PhotographersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/specialties_helper.rb
module SpecialtiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flash Photographer</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css?family=Allura|Lato:300" rel="stylesheet" type="text/css">
  <link rel="stylesheet" media="all" href="/assets/base/bootstrap.css"  type="text/css">
  <link rel="stylesheet" media="all" href="/assets/stylesheets/bootstrap/_carousel.scss"  type="text/css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<nav class="navbar navbar-inverse" >
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-brand">Flash Photographer</div>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Search Photographers", photographers_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li><a>Signed in as: <strong><%= current_user.email %></strong></a></li>
      <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete  %></li>
    <% elsif photographer_signed_in?%>
      <li><a>Signed in as Photographer: <strong><%= current_photographer.email %></strong></a></li>
      <li><%= link_to "Profile", photographer_path(current_photographer.id) %></li>
      <li><%= link_to "Edit Account", edit_photographer_registration_path%></li>
      <li><%= link_to "Sign Out", destroy_photographer_session_path, method: :delete  %></li>
    <% else %>
     <li><%= link_to "Sign Up", new_user_registration_path%> </li>
     <li><%= link_to "Sign In", new_user_session_path %> </li>
     <li><a data-toggle="modal" data-target="#myModal">Photographers</a></li>


     <div id="myModal" class="modal fade" role="dialog">
       <div class="modal-dialog">

         <div class="modal-content">
           <div class="modal-header">
             <button type="button" class="close" data-dismiss="modal">&times;</button>
             <h4 class="modal-title">Welcome Photographers</h4>
           </div>
           <div class="modal-body">
             <div class="center"
             <p>Already a member of Flash Photographer?</p>
             <%= link_to "Sign In", new_photographer_session_path, :class => 'btn btn-info'  %>
              </br>
              </br>
             <p>Or join the fastest growing website for photographers:</p>
             <%= link_to "Sign Up", new_photographer_registration_path, :class => 'btn btn-info'  %>
           </div>
         </div>

       </div>

     </div>
   </div>
    <% end %>
  </div>
</nav>

<div class="container">
  <div class="flash">
    <% if flash[:notice] %>
     <div class="alert alert-success">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:notice] %>
     </div>
    <% elsif flash.now[:alert] %>
     <div class="alert alert-danger">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash.now[:alert] %>
     </div>
    <% elsif flash[:alert] %>
     <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:alert] %>
     </div>
    <% end %>
  </div>
</div>

  <%= yield %>


</body>
<footer>
  <p>Flash Photographer, 2016 </p>
</footer>
</html>

app/views/photographers/edit.html.erb
<div class="container">
<h1><%= @photographer.first_name%> <%= @photographer.last_name %></h1>
<%= form_for @photographer do |f| %>
  <div class="form-group">
    <label for="yrs_experience">Years of experience</label>
    <%= f.text_field :yrs_experience %>
  </div>

  <div class="form-group">
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>

  <div class="form-group">
    <%= render partial: 'specialties/form', specialty: Specialty.new, photographer: @photographer  %>
  </div>

  <div class="form-group">
    <%= f.label :wttravel, class: 'checkbox' do %>
      <%= f.check_box :wttravel %> Willing to travel?
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :bio %>
    <%= f.text_area :bio, rows: 8, class: 'form-control', placeholder: "Enter personal bio" %>
  </div>

  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website, class: 'form-control', placeholder: "Enter personal website url" %></br>
  </div>

  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>
</div>

app/views/photographers/index.html.erb
<div class="container">
<h1>Find A Photographer</h1>
<%= form_tag photographers_path, method: :get %>
  <div class="form-group">
    <label for="search_zip_code">Search by zip code: </label>
    <%= text_field_tag :search_zip_code %>
  <%= submit_tag "Search", class: 'btn btn-info' %>
  </div>
<h3>
<%= @zip_code ? "Photographers located in #{@zip_code}" : "All Photographers" %>
</h3>
<% @photographers.each do |photographer| %>
  <% if photographer.confirmed? %>
    <h3><%= link_to "#{photographer.first_name} #{photographer.last_name}", photographer_path(id: photographer.id) %></h3>
    <% if photographer.yrs_experience? %>
      Years of Experience: <%= photographer.yrs_experience %>
      <% end %>

      <% if photographer.bio? %>
      <p><%= photographer.bio %> </p>
      <% end %>
  <%end%>
<%end%>
<% if @zip_code %>
  <%= link_to "All Photographers", photographers_path %>
<% end %>
</div>

app/views/photographers/show.html.erb
<div class="container">
<h1><%= @photographer.first_name%> <%= @photographer.last_name %></h1>
<h6>Years of Experience: <%= @photographer.yrs_experience %></h6>

<h4>About <%= @photographer.first_name %></h4>
<p><%= @photographer.bio %> </p>

<div class="personal">
  <p> Zip Code: <%= @photographer.zip %></br>
  Willing to travel? <%= @photographer.wttravel ? "Yes" : "No"  %></p>
  <p>Email: <%= @photographer.email %></br>
  <% if @photographer.website? %>
    Website: <%= @photographer.website %>
  <% end %>
  </p>
</div>
</div>
<div class="container">
  <% if @photographer.reviews.count >= 1 %>
  <h3>Reviews of <%=@photographer.first_name%></h3>
  <div class="reviews">
    <% @photographer.reviews.each do |review| %>
    "<%= review.comment %>"</br>
    <small>-<%= review.user.email %></small></br>
    <% if review.user == current_user %>
      <small>-<%= link_to "Delete", [review.photographer, review], method: :delete %></br>
    <%end%>
    </br>
    <% end %>
  </div>
  <% end %>
</div>
<div>
<% if current_user %>
  <h5>Write a review for <%=@photographer.first_name%>:</h5>
  <%= render 'reviews/form', review: Review.new, photographer: @photographer %>
<%end%>
</div>
<div>
<% if @photographer == current_photographer %>
  <%= link_to "Edit Profile", edit_photographer_path(@photographer) %>
<% end %>
</div>

app/views/reviews/_form.html.erb
 <%= form_for [photographer, review] do |f| %>
 <div class="rating pull-left">
    <div class="form-group" display="inline-block">

      <%#= f.text_field :rating, class: 'glphicons glyphicons-star-empty', type: "radio", value: 1 %>
     <%#= radio_button_tag(:rating, 1) %>
     <%= f.radio_button :rating, 1 %>
     <%= f.radio_button :rating, 2 %>
     <%= f.radio_button :rating, 3 %>
     <%= f.radio_button :rating, 4 %>
     <%= f.radio_button :rating, 5 %>

     <%#= f.label :rating, class: 'glyphicon glyphicon-star-empty' %>

   </div>
 </div>

    <div class="form-group">
      <%= f.label :comment, class: 'sr-only' %>
      <%= f.text_area :comment, rows: 4, class: 'form-control', placeholder: "Write a review" %>
    </div>
    <%= f.submit "Submit Review", class: 'btn btn-default pull-right' %>
  <% end %>

app/views/specialties/_form.html.erb
<%= form_for @specialty do |f| %>

   <div class="form-group">
     <%= f.label :weddings, class: 'checkbox' do %>
        <%= f.check_box :weddings %> Weddings
     <% end %>
     <%= f.label :portraits, class: 'checkbox' do %>
        <%= f.check_box :weddings %> Portraits
     <% end %>
     <%= f.label :businesses, class: 'checkbox' do %>
        <%= f.check_box :businesses %> Business Events
     <% end %>
     <%= f.label :other_specialty, class: 'sr-only' %>
     <%= f.text_box :other_specialty, class: 'form-control', placeholder: "Specialty" %>
   </div>
   <%#= f.submit "Submit Review", class: 'btn btn-default pull-right' %>
 <% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/about.html.erb
<div class="container">
<h4>Looking for a photographer?</h4>
<p>Flash photographer is the BEST place to find and connect with a photographer anywhere in the world. Search by city and state or zip code in our photographer finder, and narrow your search by specialty to find the photographer perfect for your needs!</p>
</br>
<h4>Are you a photographer?</h4>
<p>Create a profile and increase your business from the best site for photographers on the web!</p>
</div>

app/views/welcome/index.html.erb
<div class="main fill">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">

    <div class="carousel-inner" role="listbox">
      <div class="item active fill">
        <%= image_tag "Tables.jpg" %>
        <div class="carousel-caption">
          <p>Destination Weddings</p>
        </div>
      </div>
      <div class="item fill">
        <%= image_tag "Baby.jpg" %>
        <div class="carousel-caption">
          <p>Newborns</p>
        </div>
      </div>
      <div class="item fill">
        <%= image_tag "Family20.jpg" %>
        <div class="carousel-caption">
          <p>Family Portraits</p>
        </div>
      </div>
      <div class="item fill">
        <%= image_tag "Vegetation.JPG" %>
        <div class="carousel-caption">
          <p>Real Estate</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="heading">
  <div class="container-section">
  <h1><strong>Flash</br>
    Photographer</strong></h1>
    <h4>The easiest way to find a photographer <strong>anywhere</strong> for <em>any event</em>.</h4>
  </div>
</div>

<div class="container">
<div class="row">
  <div class="col-md-4">
    <div class="content">
      <img src="images/Hands.jpg" alt="Weddings" style="width:250px;height:200px;">
      <h3>Weddings</h3
        <p>Engagements, Bridals, Ceremonies, Receptions. Find a photographer for your special day.</p>
    </div>
  </div>
  <div class="col-md-4">
    <div class="content">
      <img src="images/Boys.jpg" alt="Portraits" style="width:250px;height:200px;">
      <h3>Portraits</h3
        <p>Whether it's a new baby, a graduation, or any special occasion for your family, find a photographer that can capture that priceless moment.</p>
    </div>
  </div>
  <div class="col-md-4">
    <div class="content">
      <img src="images/Nursery.jpg" alt="Nursery" style="width:250px;height:200px;">
      <h3>Corporate Events</h3
        <p>If your business is looking to visually document a social, an event or a product, we'll help find a photographer for you.</p>
    </div>
  </div>
</div>
</div>

<div class="photographers">
  <div class="container-section">
    <h1>Photographers</h1>
    <h4>Increase your business through joining a network of photographers. Thousands of users are searching for photographers, increase your clientele in minutes by creating a profile today!</h4>
    <%= link_to "Sign Up!", new_photographer_registration_path  %>
  </div>
</div>